### ISSUE TITLE
Add Package reference missing.

### ISSUE THREAD

**Issue by saviour123** [jmrog/vscode-nuget-package-manager#33]
I have install the vscode extension. After reload, the Add Package Reference does not show. Only add or remove packages show.

**Comment by jmrog** [comment]
I'm not sure that I understand the issue here. The extension should provide you with two options: "Add Package" and "Remove Package." The Add Package option works by adding a PackageReference entry to your `.csproj` file. After the package reference is added, you'll need to restore the project's dependencies so that the package gets installed (e.g., by running `dotnet restore`). Which part of that is not working here?

Maybe the issue is just that the "Add Package" command is named misleadingly, since all it actually does is add the PackageReference for the package you choose?
